### ISSUE TITLE
[QUESTION] [ERROR] [19:34:03] - Client error.

### ISSUE THREAD

**Issue by thisisash1** [NullDev/Discord-RoleShop#40]
**Your question:**

  x  [ERROR] [19:34:03] - Client error.
  x  [TRACE] [19:34:03] - DiscordAPIError[10004]: Unknown Guild
    at handleErrors (C:\Users\Administrator\Desktop\test\Discord-RoleShop\node_modules\@discordjs\rest\dist\index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:
    at async SequentialHandler.runRequest (C:\Users\Administrator\Desktop\test\Discord-RoleShop\node_modules\@discordjs\rest\dist\index.js:1021:23)
    at async SequentialHandler.queueRequest (C:\Users\Administrator\Desktop\test\Discord-RoleShop\node_modules\@discordjs\rest\dist\index.js:862:14)
    at async REST.request (C:\Users\Administrator\Desktop\test\Discord-RoleShop\node_modules\@discordjs\rest\dist\index.js:1387:22)
    at async GuildManager.fetch (C:\Users\Administrator\Desktop\test\Discord-RoleShop\node_modules\discord.js\src\managers\GuildManager.js:272:20)
    at async syncRolesAndShop (file:///C:/Users/Administrator/Desktop/test/Discord-RoleShop/src/crons/syncRolesAndShop.js:40:27)
    at async scheduleCrons (file:///C:/Users/Administrator/Desktop/test/Discord-RoleShop/src/service/cronScheduler.js:30:5)
    at async DiscordClient.<anonymous> (file:///C:/Users/Administrator/Desktop/test/Discord-RoleShop/src/bot.js:40:5)
    
 
 
 It seems that my bot is encountering the following error messages. However, bot is logged in with 'do not disturb' status on Discord, and the bot appears to be functioning normally.
 <img width="110" alt="스크린샷 2023-11-16 오후 7 37 56" src="https://github.com/NullDev/Discord-RoleShop/assets/124415282/c4e175e9-cab8-47aa-95e1-dff501e0d21b">

Even though I've correctly entered all the tokens in custom.js, I'm still getting the same error. I've tried putting both the bot ID and the Discord ID of the bot owner in bot_owner_ids, but the issue persists.

Can you help identify the cause of this error?

**Comment by NullDev** [comment]
Hello! Thanks for reporting this. 
That was a bug in the code and not your fault, sorry about that. 
It should be fixed now with https://github.com/NullDev/Discord-RoleShop/commit/156b5c8a429da53a4e78a9e62bf312000d69e4ff .
Please let me know if the problem persists.

**Comment by thisisash1** [comment]
thanks a lot! it works!
